[program:torrent-server]
directory=/app/torrent-server
command=node server.js
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/torrent-server.err.log
stdout_logfile=/var/log/supervisor/torrent-server.out.log
environment=NODE_ENV="production",PORT="8002"
